// <auto-generated />
namespace BanHangOnline.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Update2003 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update2003));
        
        string IMigrationMetadata.Id
        {
            get { return "202303201516080_Update2003"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
